name: em-ccdorc
home: https://github.com/hmcts/em-ccd-orchestrator
version: 2.0.11
apiVersion: v2
description: HMCTS EM - CCD Orchestrator API
maintainers:
  - name: HMCTS EM Team
dependencies:
  - name: java
    version: 4.2.0
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
