name: em-ccdorc
home: https://github.com/hmcts/em-ccd-orchestrator
version: 2.0.25
apiVersion: v2
description: HMCTS EM - CCD Orchestrator API
maintainers:
  - name: HMCTS EM Team
dependencies:
  - name: java
    version: 5.2.1
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
