name: em-ccdorc
home: https://github.com/hmcts/em-ccd-orchestrator
version: 1.0.0
apiVersion: v2
description: HMCTS EM - CCD Orchestrator API
maintainers:
  - name: HMCTS EM Team
dependencies:
  - name: java
    version: 3.4.2
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/