name: em-ccdorc
home: https://github.com/hmcts/em-ccd-orchestrator
version: 1.0.17
apiVersion: v2
description: HMCTS EM - CCD Orchestrator API
maintainers:
  - name: HMCTS EM Team
dependencies:
  - name: java
    version: 4.0.1
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
