title: IAC Upper Tribunal Bundle
filename: Upper-Tribunal-Bundle.pdf
filenameIdentifier: /case_details/case_data/bundleFileNamePrefix
coverpageTemplate: TB-IAC-GNO-ENG-00746.docx
hasTableOfContents: true
hasCoversheets: true
documentNameValue: /document/document_filename
documentLinkValue: /document
sort:
  field: /dateUploaded
  order: ascending
hasFolderCoversheets: true
pageNumberFormat: numberOfPages
folders:
  - name: FTPA Appellant documents
    documents:
      - type: documentSet
        property: /ftpaAppellantDocuments
  - name: FTPA Respondent documents
    documents:
      - type: documentSet
        property: /ftpaRespondentDocuments
  - name: Decisions and reasons documents
    documents:
      - type: documentSet
        property: /finalDecisionAndReasonsDocuments
  - name: Hearing documents
    documents:
      - type: documentSet
        property: /hearingDocuments
        filters:
          - property : /tag
            value : caseSummary
      - type: documentSet
        property: /hearingDocuments
        filters:
          - property: /tag
            value: hearingRequirements
      - type: documentSet
        property: /hearingDocuments
        filters:
          - property: /tag
            value: hearingNotice
  - name: Appellant documents
    documents:
      - type: documentSet
        property: /legalRepresentativeDocuments
        filters:
          - property: /tag
            value: caseArgument
      - type: documentSet
        property: /legalRepresentativeDocuments
        filters:
          - property: /tag
            value: homeOfficeDecisionLetter
      - type: documentSet
        property: /legalRepresentativeDocuments
        filters:
          - property: /tag
            value: appealSubmission
  - name: Respondent documents
    documents:
      - type: documentSet
        property: /respondentDocuments
  - name: Evidence supplied after the hearing bundle documents
    documents:
      - type: documentSet
        property: /appellantAddendumEvidenceDocs
        filters:
          - property: /tag
            value: addendumEvidence
      - type: documentSet
        property: /respondentAddendumEvidenceDocs
        filters:
          - property: /tag
            value: addendumEvidence
