title: SSCS Bundle
filename: EditedSscsBundle.pdf
filenameIdentifier: /case_details/id
coverpageTemplate: SSCS-cover-page.docx
hasTableOfContents: true
hasCoversheets: true
sort:
  field: /documentDateAdded
  order: ascending
hasFolderCoversheets: false
pageNumberFormat: numberOfPages
documentNameValue: /documentFileName
customDocument: true
customDocumentLinkValue: /editedDocumentLink
folders:
  - name: DWP
    documents:
      - type: documentSet
        property: /dwpDocuments
        filters:
          - property: /documentType
            value: dwpResponse
      - type: documentSet
        property: /dwpDocuments
        filters:
          - property: /documentType
            value: dwpEvidenceBundle
  - name: Further Additions
    documents:
      - type: documentSet
        property: /sscsDocument
        filters:
          - property: /bundleAddition
            value: \w+
      - type: document
        property: /audioVideoEvidenceBundleDocument
