title: SSCS Bundle
filename: UneditedSscsBundle.pdf
filenameIdentifier: /case_details/id
coverpageTemplate: SSCS-cover-page.docx
hasTableOfContents: true
hasCoversheets: true
sort:
  field: /documentDateAdded
  order: ascending
hasFolderCoversheets: true
pageNumberFormat: numberOfPages
documentNameValue: /documentFileName
folders:
  - name: DWP
    documents:
      - type: documentSet
        property: /dwpDocuments
        filters:
          - property: /documentType
            value: dwpEvidenceBundle
      - type: documentSet
        property: /dwpDocuments
        filters:
          - property: /documentType
            value: dwpResponse
  - name: Original Documents
    documents:
      - type: documentSet
        property: /sscsDocument
        filters:
          - property: /bundleAddition
            value: \w+
  - name:  Translated Documents
    documents:
      - type: documentSet
        property: /sscsWelshDocuments
        filters:
          - property: /bundleAddition
            value: \w+
