title: SSCS Bundle Edited
filename: EditedSscsBundle.pdf
filenameIdentifier: /case_details/id
coverpageTemplate: SSCS-cover-page.docx
hasTableOfContents: true
hasCoversheets: true
hasFolderCoversheets: false
pageNumberFormat: numberOfPages
documentNameValue: /documentFileName
customDocument: true
customDocumentLinkValue: /editedDocumentLink
folders:
  - name: DWP
    documents:
      - type: documentSet
        property: /dwpDocuments
        filters:
          - property: /documentType
            value: dwpResponse
      - type: documentSet
        property: /dwpDocuments
        filters:
          - property: /documentType
            value: dwpEvidenceBundle
  - name: Further additions
    documents:
      - type: documentSet
        property: /sscsDocument
        filters:
          - property: /bundleAddition
            value: \w+
      - type: document
        property: /audioVideoEvidenceBundleDocument
      - type: documentSet
        property: /sscsDocument
        filters:
          - property: /statementOfEvidencePdf
            value: \w+
      - type: documentSet
        property: /dwpDocuments
        filters:
          - property: /rip1DocumentLink
            value: \w+
